### ISSUE TITLE
OBS websocket authentication error

### ISSUE THREAD

**Issue by Rawh** [isaac-jordan/obs-screen-recognition#10]
Hi, 

Trying to run the script and getting an authentication error. The OBS websocket script is installed and has a password set to it. The reason is because I'm also using a streamdeck and the "OBS Tools" from barraider, which strongly advises you to put a password on the websocket.

The error:

```
C:\gitrepos\obs-screen-recognition>python obs_screen_recognition_script.py ./hll
Running with settings: {'monitor_to_capture': 1, 'screen_format': '1080p', 'default_scene_name': 'Scene', 'target_scene_name': 'Scene (map covered)', 'num_features_to_detect': 500, 'num_good_matches_required': 20}
Traceback (most recent call last):
  File "obs_screen_recognition_script.py", line 140, in <module>
    main()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "obs_screen_recognition_script.py", line 115, in main
    obs.connect()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\obswebsocket\core.py", line 70, in connect
    self._auth(self.password)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\obswebsocket\core.py", line 140, in _auth
    raise exceptions.ConnectionFailure(result['error'])
obswebsocket.exceptions.ConnectionFailure: Authentication Failed.
```

Where can I set the password for the the obs*.py script? I have tried to read --help, but there are no options for it. I have also tried to paste the password behind "./hll", but as it has special characters, python has a booboo :-) 

```
C:\gitrepos\obs-screen-recognition>python obs_screen_recognition_script.py --help
Usage: obs_screen_recognition_script.py [OPTIONS] RESOURCE_DIR

Options:
  --show-debug-window
  --help               Show this message and exit.
```

**Comment by isaac-jordan** [comment]
Unfortunately, the tool doesn't have support for a password yet - however it makes sense to add one, so I'll leave this issue open :)

**Comment by Elenedeath** [comment]
Open obs_screen_recognition_script.py with a text editor like notepad++ or atom
on line 17 next after
`host = "localhost"
port = 4444`

insert this
`password = "Test1234"`

on line 124 change the line
`obs = obsws(host, port)`

to

`obs = obsws(host, port, password)`

Done your script connect to a websocket protected with password

**Comment by isaac-jordan** [comment]
Resolved in https://github.com/isaac-jordan/obs-screen-recognition/commit/8c3bb5c3a41aa0bf5553e2d6bceb416fab2a6c3f

You can now use the command @Elenedeath mentioned above.
