### ISSUE TITLE
no reaction

### ISSUE THREAD

**Issue by DeBoerd** [isaac-jordan/obs-screen-recognition#2]
I installed the mss module. The problem of my predecessor. The script doesn´t work.

script log is empty

**Comment by isaac-jordan** [comment]
Hey, please confirm how you are running this script. It is *not* designed to ran as an OBS script from *inside* OBS. It's designed to be run separately using the CLI.

Check out the instructions in the readme :)

**Comment by DeBoerd** [comment]
When the script starts it goes out again. (windows 10, 64bit)

I also tried it via CMD:

`C:\ProgramData\obs-studio-hook\obs-studio\obs-plugins\64bit>obs_screen_recognition_script.py
Traceback (most recent call last):
  File "C:\ProgramData\obs-studio-hook\obs-studio\obs-plugins\64bit\obs_screen_recognition_script.py", line 133, in <module>
    main()
  File "C:\ProgramData\obs-studio-hook\obs-studio\obs-plugins\64bit\obs_screen_recognition_script.py", line 89, in main
    application_settings = json.load(settings_file)
  File "C:\Users\Boerd\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Boerd\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Boerd\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Boerd\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 27 (char 57)`

**Comment by isaac-jordan** [comment]
(Sorry for the late reply)

It looks like from the stacktrace that you're running the script as an OBS plugin. As the README says, it shouldn't be run as an OBS plugin, and should be run entirely separately from OBS (it communicates with OBS, but does not run within OBS).

Resolving this for now. Let me know if there are other questions.
